### ISSUE TITLE
Question: speed of scraping?

### ISSUE THREAD

**Issue by BradKML** [Arjun-Siva/Instagram-Network_scraping_and_analysis#2]
This project looks interesting! What is the speed of the crawler in relations to the amount of users?
Also are there any ways around it? https://github.com/instautils/spider

**Comment by Arjun-Siva** [comment]
@BrandonKMLee I scraped the user accounts in batches. When scrolling through the follower/following list of an account, it kept loading without fetching any new data. This usually happens after scraping 6,7 accounts continuously. For some reason, Instagram loading time throttled when scraping after these many accounts. Also, when scraping user accounts with lots of followers/following, say more than 2000, Instagram throttled after fetching a few hundred followers. So I didn't scrape those accounts. Another major issue was Instagram detecting bot activity. Every time I had to sign in on Instagram on Firefox geckodriver. Instagram also blocks the account if a frequent signing-in activity is found. I had to reset my password many times to unblock it.
